site_name: Dockwatch Wiki
site_author: nitsua
site_description: Simple UI driven way to manage updates & notifications for Docker containers.
site_url: https://dockwatch.wiki
repo_name: dockwatch
repo_url: https://github.com/Notifiarr/dockwatch
repo_wiki_name: dockwatch-wiki
repo_wiki_url: https://github.com/Notifiarr/dockwatch-wiki

nav:
  - Dockwatch:
    - About: index.md
    - UI:
      - Overview: pages/overview/index.md
      - Containers:
        - Table: pages/containers/table.md
        - Groups: pages/containers/groups.md
        - Updates: pages/containers/updates.md
      - Compose: pages/compose/index.md
      - Orphans: pages/orphans/index.md
      - Notifications:
        - Notifiarr: pages/notifications/notifiarr.md
        - Telegram: pages/notifications/telegram.md
      - Settings:
        - General: pages/settings/general.md
        - Logins: pages/settings/logins.md
        - Servers: pages/settings/servers.md
        - Containers: pages/settings/containers.md
        - Prune: pages/settings/prune.md
        - Thresholds: pages/settings/thresholds.md
        - SSE: pages/settings/sse.md
        - Logging: pages/settings/logging.md
        - Development: pages/settings/development.md
      - Tasks: pages/tasks/index.md
      - Commands:  pages/commands/index.md
      - Logs: pages/logs/index.md
  - Requirements: pages/misc/requirements.md
  - Compose/Run: pages/misc/composeRun.md
  - Logins: pages/misc/logins.md
  - Dependencies: pages/misc/dependencies.md
  - Socket proxy: pages/misc/proxy.md
  - Swarm: pages/misc/swarm.md
  - API: pages/misc/api.md
  - Misc:
    - Images: pages/misc/images.md
  - Contributing: pages/misc/contributing.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Dark mode

extra_css:
  - stylesheets/github-permalink-style.css

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - search

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - toc:
      toc_depth: 4
      permalink: ''
